// Code generated by "stringer -type Event"; DO NOT EDIT.

package equinox

import "fmt"

const _Event_name = "MESSAGE_PRE_ANALYZEMESSAGE_ANALYZEMESSAGE_POST_ANALYZEHANDLER_PRE_EXECUTEHANDLER_POST_EXECUTELAST_RESORT_PRE_EXECUTELAST_RESORT_POST_EXECUTEMENTION_FOUND"

var _Event_index = [...]uint8{0, 19, 34, 54, 73, 93, 116, 140, 153}

func (i Event) String() string {
	if i < 0 || i >= Event(len(_Event_index)-1) {
		return fmt.Sprintf("Event(%d)", i)
	}
	return _Event_name[_Event_index[i]:_Event_index[i+1]]
}
