package equinox

type Event int

const (
    MESSAGE_PRE_ANALYZE  Event = iota
    MESSAGE_ANALYZE
    MESSAGE_POST_ANALYZE

    MESSAGE_CHECK_MENTIONS
    MESSAGE_CHECK_OUR_MENTIONS

    HANDLER_PRE_EXECUTE
    HANDLER_POST_EXECUTE
)
