// Code generated by "stringer -type Event"; DO NOT EDIT

package equinox

import "fmt"

const _Event_name = "MESSAGE_PRE_ANALYZEMESSAGE_ANALYZEMESSAGE_POST_ANALYZEMESSAGE_CHECK_MENTIONSMESSAGE_CHECK_OUR_MENTIONSHANDLER_PRE_EXECUTEHANDLER_POST_EXECUTELAST_RESORT_PRE_EXECUTELAST_RESORT_POST_EXECUTE"

var _Event_index = [...]uint8{0, 19, 34, 54, 76, 102, 121, 141, 164, 188}

func (i Event) String() string {
	if i < 0 || i >= Event(len(_Event_index)-1) {
		return fmt.Sprintf("Event(%d)", i)
	}
	return _Event_name[_Event_index[i]:_Event_index[i+1]]
}
