// Code generated by "stringer -type Context parser.go"; DO NOT EDIT.

package annotations

import "fmt"

const _Context_name = "CONTEXT_ROOTCONTEXT_ANNOTATIONCONTEXT_PARAMSCONTEXT_STRINGCONTEXT_COMMENT"

var _Context_index = [...]uint8{0, 12, 30, 44, 58, 73}

func (i Context) String() string {
	i -= 7
	if i < 0 || i >= Context(len(_Context_index)-1) {
		return fmt.Sprintf("Context(%d)", i+7)
	}
	return _Context_name[_Context_index[i]:_Context_index[i+1]]
}
